### ISSUE TITLE
Issue running grpc-dynamic-gateway

### ISSUE THREAD

**Issue by gwihlidal** [konsumer/grpc-dynamic-gateway#2]
I am having some issues using grpc-dynamic-gateway, and I was hoping to get some ideas or help from you on getting things working (or tell me if I’m doing something wrong).
 
My own proto file is failing, but I tried to run it against the example/api.proto file in the repository, and I am getting the same service.children error, as 'children' on the service instance seems to be undefined.
 
```
C:\ grpc-dynamic-gateway-master>node example example/api.proto 5050 ./example/api.js
C:\grpc-dynamic-gateway-master\example\index.js:35
      **proto[p][t].service.children.forEach(c => {**
                                  ^
 
**TypeError: Cannot read property 'forEach' of undefined**
    at Object.keys.forEach.t (C:\Users\graham\Desktop\grpc-dynamic-gateway-master\grpc-dynamic-gateway-master\example\index.js:35:35)
    at Array.forEach (native)
    at Object.keys.forEach.p (C:\Users\graham\Desktop\grpc-dynamic-gateway-master\grpc-dynamic-gateway-master\example\index.js:32:25)
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\graham\Desktop\grpc-dynamic-gateway-master\grpc-dynamic-gateway-master\example\index.js:31:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
 
A few questions:
 
1.	Do you know why I would get an error like that?
2.	You have a an empty stubbed out annotations.proto file with your test.proto 
a.	Why is it stubbed instead of the one from grpc-gateway?
b.	With the stub, the http options attribute wouldn’t parse it seems, or am I missing something?
3.	The install docs for grpc-dynamic-gateway says to do this: 
a.	npm -g grpc-dynamic-gateway
b.	I presume it’s a typo and it should be npm install?

Thank you,
Graham

**Comment by konsumer** [comment]
This is a few issues, but I will try to address them.

[Here](https://github.com/konsumer/grpc-demo) is a full example project with grpc client/server/gateway that includes all the proto files and everything, setup the way I would expect, but I need to work out the upstream grpc module API changes, which are breaking and don't seem to be documented. 

I am updating grpcnode & this project. Very frustrating, as the interface is different enough to break a lot of things. At some point, I'd like to switch to direct parsing of everything using [protobufjs](https://www.npmjs.com/package/protobufjs), so the interface isn't so flakey. It will take a bit of work, and I'll have to re-implement some of grpc's stuff, also I am pretty busy, so short on time. For now, I am going through and updating my stuff to work with google's unstable API grpc, but even that will take time, and it doesn't seem like it all works the way it did before. I posted a simple example in [this issue](https://github.com/grpc/grpc/issues/12135) that illustrates the biggest issue, which seems to be currently undocumented changes in the API.


1. I think I have gotten this in the past when I didn't have a `package` setup correctly, or I give it the wrong paths, but I think this is happening because of the upstream changes, in this case.
2. It's because google's grpc node library does it's own validation of http annotations, so you don't really need the annotations import, but I keep it imported so it looks like it would look in my own projects, where I include the real google API protos (for use with protoc and such.) In my example repo above, I included the full thing. I will get rid of examples in a few of my projects and point to that repo, so I have 1 central test for everything, that is a better and more complete example.
3. Yep, typo, fixed. Thanks for the catch.


Here is what I get with that demo project:

```
npm run ls
> grpc-demo@1.0.0 ls /Users/konsumer/WORKSPACE/grpc-demo
> grpc-client ls -I ./proto helloworld.proto

Methods:
  helloworld.Greeter.SayHello(GreeterRequest) → GreeterReply
  helloworld.Greeter.SayGoodbye(GreeterRequest) → GreeterReply

Message-types:
  helloworld.GreeterRequest: {"name":""}
  helloworld.GreeterReply: {"message":""}
```

```
npm run grpc

> grpc-demo@1.0.0 grpc /Users/konsumer/WORKSPACE/grpc-demo
> grpc-server --host localhost:50051 -I ./proto helloworld.proto helloworld.js

helloworld.Greeter.SayHello added.
helloworld.Greeter.SayGoodbye added.
gRPC protobuf server started on localhost:50051
```

```
npm run gateway

> grpc-demo@1.0.0 gateway /Users/konsumer/WORKSPACE/grpc-demo
> grpc-dynamic-gateway -g localhost:50051 -I ./proto helloworld.proto

POST /v1/hi
POST /v1/bye
Listening on http://0.0.0.0:8080, proxying to gRPC on localhost:50051
```

```
npm test
> grpc-demo@1.0.0 test /Users/konsumer/WORKSPACE/grpc-demo
> grpc-client run --host localhost:50051 -I ./proto helloworld.proto -m helloworld.Greeter.sayHello -a '{"name": "World"}'

{
  "message": "Hello World"
}
```

**Comment by konsumer** [comment]
Ok, got everything updated to basically work in [the demo project](https://github.com/konsumer/grpc-demo). Use that as a starter, lemme know if you have issues.

**Comment by gwihlidal** [comment]
Thanks for the great reply. I tried running the demo project, and it does get much further than before! There is still an issue it seems, or something I'm doing wrong. The server runs fine, as well as the gateway, but the client test throws an error.

`C:\Users\graham\Desktop\grpc-demo-master>npm run grpc

> grpc-demo@1.0.0 grpc C:\Users\graham\Desktop\grpc-demo-master
> grpc-server --host localhost:50051 -I ./proto helloworld.proto helloworld.js

helloworld.Greeter.SayHello added.
helloworld.Greeter.SayGoodbye added.
gRPC protobuf server started on localhost:50051`

`C:\Users\graham\Desktop\grpc-demo-master>npm run gateway

> grpc-demo@1.0.0 gateway C:\Users\graham\Desktop\grpc-demo-master
> grpc-dynamic-gateway -g localhost:50051 -I ./proto helloworld.proto

POST /v1/hi
POST /v1/bye
Listening on http://0.0.0.0:8080, proxying to gRPC on localhost:50051`

`C:\Users\graham\Desktop\grpc-demo-master>npm test

> grpc-demo@1.0.0 test C:\Users\graham\Desktop\grpc-demo-master
> grpc-client run --host localhost:50051 -I ./proto helloworld.proto -m helloworld.Greeter.SayHello -a '{"name": "World"}'

undefined:1
'{name:
^

SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at main (C:\Users\graham\Desktop\grpc-demo-master\node_modules\grpcnode\client.js:163:73)
    at Object.<anonymous> (C:\Users\graham\Desktop\grpc-demo-master\node_modules\grpcnode\client.js:194:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! Test failed.  See above for more details.

C:\Users\graham\Desktop\grpc-demo-master>`

**Comment by gwihlidal** [comment]
The gateway and server do seem to be working correctly though, as I successfully used PostMan to invoke the REST api.

![image](https://user-images.githubusercontent.com/564042/29163674-7c5410f0-7dbd-11e7-9d8c-1f43e29f4343.png)

So seems like just an issue with the client?

Thanks!
Graham

**Comment by konsumer** [comment]
That's good news. I can't seem to recreate the client issue, but it is probably something silly. I had to change a lot of code, and I probably missed something. [Here](https://asciinema.org/a/LYY6hCNInKgLPPFwL54V5Ka5m) is a screencast of it working from scratch for me. The pause between `npm i` and `npm test` is me opening another tab and running `npm run grpc`. Are you on Windows? it might be escaping the JSON correctly or something.

**Comment by konsumer** [comment]
Maybe try just running on the console something like this:

```
grpc-client run --host localhost:50051 -I ./proto helloworld.proto -m hellowor
ld.Greeter.SayHello -a '{"name": "World"}'
```

after you do `npm i -g grpcnode` to get grpc-client in your path.

**Comment by gwihlidal** [comment]
Sorry for taking so long to get back to this; grpc-dynamic-gateway seems to work now after your changes. Thank you!
